name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: centos7

    steps:
    - name: Git pull
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: aliyun1525156146
        password: chentao712
        logout: false
        
    - name: Install Skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo
        
    - name: Sync Mongo Image to Aliyun
      run: |
         skopeo copy docker://docker.io/library/mongo:5.0.27 docker://registry.cn-hangzhou.aliyuncs.com/your-aliyun-repo/mongo:5.0.27
